### ISSUE TITLE
Use DID pointer internally

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/warp-dart#24]
The core problem I am noticing overall is that externally, DID is not being dropped or freed, which overtime can lead to memory leaks. To get around this problem, DID class may need to be changed so it uses a string but internally would convert to a pointer when passing to one of the functions that needs it. This way, we can free the pointer after using it and not worry about possible memory leaks.

**Comment by tooshel** [comment]
Is this something you are working on now @dariusc93?

**Comment by dariusc93** [comment]
Not at the moment. Might tackle it later since it is a simple change
